### ISSUE TITLE
Debug Toolbar and Asset processing with Grunt

### ISSUE THREAD

**Issue by dougfelton** [samdark/yii2-cookbook#101]
In "Asset processing with Grunt", you suggest turning off Yii asset management completely by doing the following:

```php
'bundles' => false,
```
In my experience, that is not the best method because, in addition to turning off the asset management for all the assets you are adding via Grunt, it also causes Yii not to load the debug toolbar assets.  So instead of setting bundles to false across the board, I do the following:

```php
'bundles' => [
    'yii\web\JqueryAsset' => false,
    'yii\bootstrap\BootstrapAsset' => false,
    'yii\web\YiiAsset' => false,
    'yii\validators\ValidationAsset' => false,
    'yii\widgets\ActiveFormAsset' => false
],
```
That way, yii\debug\ToolbarAsset will still load and the debug toolbar will be visible and functional.

**Comment by samdark** [comment]
Thanks!
