### ISSUE TITLE
Cookbook articles and official guide 

### ISSUE THREAD

**Issue by summerknight** [samdark/yii2-cookbook#104]
There are some topics not covered already:

- How component works
- Configuring components globally
- Customizing 404 page
- Handling errors and exceptions
- Understanding error stack trace
- A safe approach to passwords explained

etc.

Some of them (or most of them) are explained in official guides. So what is the purpose to include such topics in cookbook?

My suggestion and offer:

- Let's organize cookbook in a problem-solution manner. And use a proper headers for such section. Like cookbook for Yii1. May be I'm wrong but now this Yii2 cookbook it is not fully organized this way 
- Explain topics in a manner of example. I mean more examples less text
- Organize recipe in a manner copy-paste-use without a necessity to read a lot of text (guide problem in some cases)

As a result in comparison with guide cookbook will provide a quick solutions for typical situations. Without a necessity to spend a lot of time to study concepts. 

What do you think?

**Comment by samdark** [comment]
You're right that some of these are covered and covered well. TOC was initially suggested by community while guide was still incomplete. I think it's safe to eliminate some of the topics.

Problem-solution recipes are OK. Copy-paste w/o explaination isn't. The purpose of the project is to give better understanding while providing solutions.

**Comment by summerknight** [comment]
Sure, I mean code is ready to use by copy-paste without any explanation. But explanation is also provided. And completely based on a concrete practical case. 

So, my suggestions about possible recipe structure:

- section "Problem", where problem case is explained by example. Very simple to understand the concept.
- section "Anti pattern" (optional) - solution not based on Yii features thus is not good.
- section "Solution" - solution explanation based on Yii features, by example
- section "Notes" (optional) - additional notes, remarks, conclusion
- section "See also" - at least a link on the Yii official guide, in order to avoid Yii guide duplication.

Maybe it is better for [cookies recipe](https://github.com/samdark/yii2-cookbook/blob/master/book/cookies.md) to be moved to Yii official guide cookie section. 

About RBAC recipe:
> Despite being described well in official guide there's no complete example on how to use it. Let's fill the gap.
Is it ok to fill such gap in the cookbook? Maybe better to complete the Yii guide example?

Actually I don't know. I have time and desire to write something from time to time for the cookbook.
And have to understand what is good and what is not good for cookbook project in order to provide better articles and do not duplicate existed somewhere information.

Thank you, Alexander. This issue will help me to make your project better.

**Comment by samdark** [comment]
I don't think we should mention anti-patterns at all if these aren't common enough to be used by everyone.

Improving the guide is OK but the guide isn't complete by-example thing. There are examples in the guide, of course, but these are small. There's no plan to add long step-by-step tutorials there. The cookbook, on the other hand, is a good place for these.

**Comment by samdark** [comment]
As for structure, it's OK for it to vary but in general. I prefer it to be structured as https://github.com/samdark/yii2-cookbook/blob/master/book/security-rbac.md.

**Comment by summerknight** [comment]
Thank you, Alexander, for explanations. Now everything is clear.
