### ISSUE TITLE
Update ide-autocompletion.md

### ISSUE THREAD

**Issue by LAV45** [samdark/yii2-cookbook#121]
https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md
Вот мой вариант использования
https://github.com/LAV45/yii2-translated-behavior-demo/blob/master/Yii.php
Оставил только описание классов, для работы autocompletion в IDE этого достаточно.

https://github.com/LAV45/yii2-translated-behavior-demo/blob/master/Yii.php#L57
если нужен только autocompletion тогда не зачем создавать отдельный класс User и переопределять его в настройках.

**Comment by samdark** [comment]
Спасибо!
