### ISSUE TITLE
ActiveForm.js: добавленные поля не валидируются по «blur»

### ISSUE THREAD

**Issue by w3lifer** [samdark/yii2-cookbook#129]
Изначально у меня есть такое поле:

``` js
{
    "id": "source-0-title",
    "name": "[0]title",
    "container": ".field-source-0-title",
    "input": "#source-0-title",
    "validate": function(attribute, value, messages, deferred, $form) {
      yii.validation.required(value, messages, {
        "message": "Source Title cannot be blank."
      });
}
```

Я добавляю новое (путем глубокой копии существующей разметки исходного поля и обработки его HTML-атрибутов):

``` js
{
    "id": "source-1-title",
    "name": "[1]title",
    "container": ".field-source-1-title",
    "input": "#source-1-title",
    "validate": function(attribute, value, messages, deferred, $form) {
      yii.validation.required(value, messages, {
        "message": "Source Title cannot be blank."
      });
}
```

Если поставить курсор в только что добавленное поле, а затем кликнуть вне его, то ничего не происходит; при этом при отправке формы оно валидируется. Также, если поставить курсор в исходное поле, а затем кликнуть вне его, то валидируется не только оно, но и добавленное.

**Comment by w3lifer** [comment]
В общем, я&nbsp;— болван&nbsp;...
В суматохе написания JavaScript-скрипта я добавлял правила валидации до того, как вставил разметку в документ!

**Comment by thiagotalma** [comment]
This is an international collaborative project (like most open source projects).

Please use the http://translate.google.com and rewrite the issue in English.

**Comment by samdark** [comment]
@thiagotalma no need to in this case. It's something in his code that was broken and he found it out after writing down a question (happens all the time).

**Comment by thiagotalma** [comment]
@samdark In my opinion, we take care of projects should require that the issues are always written in English.
Someday someone else with the same problem can find the solution in a search. But you will not find if it is written in Russian.
My native language is Brazilian Portuguese. Do you think it would make sense if I discuss issues written in Portuguese?

Cheers!

**Comment by samdark** [comment]
Yeah. I agree.
