### ISSUE TITLE
Add tablename to ar-single-table-inheritance

### ISSUE THREAD

**Issue by dhoomm** [samdark/yii2-cookbook#147]
This prevents duplicate column names in joins.
`class SportCar/HeavyCar extends Car` the `find` function should also pass the table name to CarQuery

 `return new CarQuery(get_called_class(), ['type' => self::TYPE,'tableName'=>  self::tableName()]);`. 

Then add a property `$tableName` to `class CarQuery`.
Then use it in `function prepare` as 

`$this->andWhere(["$this->tableName.type" => $this->type]);`

When creating a join with a table having column name 'type' wont create conflict..

**Comment by samdark** [comment]
Would you please make a pull request?

**Comment by dhoomm** [comment]
created at https://github.com/samdark/yii2-cookbook/pull/148
