### ISSUE TITLE
Suggestion: A summary that includes the basic methods that article depends on.

### ISSUE THREAD

**Issue by saidbakr** [samdark/yii2-cookbook#149]
Suppose [Reusing views via partials](https://github.com/samdark/yii2-cookbook/blob/master/book/reusing-views-via-partials.md), this article depends on [`View render method`](http://www.yiiframework.com/doc-2.0/yii-base-view.html#render%28%29-detail), so in that supposed summary a link to that method in the api should be regarded.

**Comment by samdark** [comment]
Agree.
