### ISSUE TITLE
"Destination web/js/jquery.min.js not written because src files were empty."  with structure-asset-processing-with-grunt.md

### ISSUE THREAD

**Issue by b987123** [samdark/yii2-cookbook#155]
Hi 
If I follow the guide, first I'm getting some errors because of grunt dependencies, 
but over all 'grunt build'  returns 

>> Destination web/js/jquery.min.js not written because src files were empty.

The browser debugging console shows some missing file lib.min.js which I can't find anywhere.
 http://yii2-basic.mydomain.com/js/lib.min.js?v= 

What might be the problem?

**Comment by samdark** [comment]
Source file for jquery is empty.
