### ISSUE TITLE
403 Forbidden at readthedocs.io

### ISSUE THREAD

**Issue by Nex-Otaku** [samdark/yii2-cookbook#157]
http://yii2-cookbook.readthedocs.io/ gives "403 Forbidden" error.

Please fix!

**Comment by samdark** [comment]
The URL is https://yii2-cookbook.readthedocs.org/README/. Not sure it's possible to alias index page to readme.

**Comment by Nex-Otaku** [comment]
Just rename "book/README.md" to "book/index.md".

I have tested it on fork.

**Comment by samdark** [comment]
https://yii2-cookbook.readthedocs.io/
