### ISSUE TITLE
DOC: yiiactiveform.js

### ISSUE THREAD

**Issue by dicrtarasov** [samdark/yii2-cookbook#191]
Page: https://yii2-cookbook.readthedocs.io/forms-activeform-js/
Paragraph: "Getting Attribute Value"

The code is not working:
```javascript
$('#form_id').yiiActiveForm('find', '#attribute').value
```
The right is:
```javascript
$('#form_id').yiiActiveForm('find', 'attribute').value
```

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/commit/e98999d22b4852eb6a1739a49dbad5adb847e70d Thanks!
