### ISSUE TITLE
Yii Cookbook isnt displaying properly

### ISSUE THREAD

**Issue by buttflattery** [samdark/yii2-cookbook#197]
hi the view of the menu is somehow not correctly displayed on the link https://yii2-cookbook.readthedocs.io/forms-activeform-js/, see below image 

![image](https://user-images.githubusercontent.com/1536454/47305590-5f9bd080-d643-11e8-8bca-4f1259de6d24.png)

**Comment by buttflattery** [comment]
still the same, after 8 days. This is annoying as cant look into the cookbook for any references, specially activeform

**Comment by samdark** [comment]
You can. Just use github. I've removed the link to readthedocs as I have no idea on how to fix it.

**Comment by adhayward** [comment]
Looking at [the mkdocs documentation](https://www.mkdocs.org/user-guide/styling-your-docs/#built-in-themes) this looks like the page has switched from the readthedocs theme to the mkdocs theme - maybe they changed the default.
I can't see the mkdocs.yml file in the repo but specifying the theme as readthedocs should put it back to a side navigation bar.
Alternatively, you can [also specify nav in the mkdocs.yml](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation) to manually build the nav bar and put everything into dropdowns and reduce the size of the top level menu.

Hopefully, this is of some use to getting this fixed.
