### ISSUE TITLE
Cookie Problem on I18n selecting application language

### ISSUE THREAD

**Issue by sercey** [samdark/yii2-cookbook#39]
This documents are perfect but having some problems.
In **I18n selecting application language** page 

    $languageCookie = new Cookie([
        'name' => 'language',
        'value' => $language,
        'expire' => 60 * 60 * 24 * 30, // 30 days
    ]);
    Yii::$app->request->cookies->add($languageCookie);

I think its should be

    $languageCookie = new Cookie([
        'name' => 'language',
        'value' => $language,
        'expire' => time() + (60 * 60 * 24 * 30), // 30 days
    ]);
    Yii::$app->response->cookies->add($languageCookie);

thanks.

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Thanks!
