### ISSUE TITLE
Using locale in URL for Yii2 to make multi-lingual sites, best practices

### ISSUE THREAD

**Issue by uran1980** [samdark/yii2-cookbook#4]
* Multi-lingual sites based on routes (How to add locale short aliases like usually used **en**, **ru**, instead of long locale tags like **en-US**, **ru-RU** etc.)
* Multi-lingual sites based on subdomains
* Best practices
* Tips & tricks

**Comment by samdark** [comment]
Started it: https://github.com/samdark/yii2-cookbook/blob/master/book/i18n-selecting-application-language.md

**Comment by uran1980** [comment]
Greate :+1
