### ISSUE TITLE
Asset processing with Grunt page missing grunt-contrib-copy line

### ISSUE THREAD

**Issue by dougfelton** [samdark/yii2-cookbook#43]
Thank you for the "Asset processing with Grunt"  page.  It helped me tremendously.

Wanted you to know that the section which describes the node modules to install is missing this line:

npm install grunt-contrib-copy --save-dev

**Comment by samdark** [comment]
What's the purpose? It works w/o it for me.

**Comment by dougfelton** [comment]
The Gruntfile as written will not copy the font directory without first installing grunt-contrib-copy.  The method for installing all of the other required plugins is listed at the top of the page, but that plugin is omitted.  The purpose for adding it is for completeness.  All of the other plugins required by the Gruntfile are listed, but grunt-contrib-copy is not.  If it works without it for you, then you already had that plugin installed... but I am assuming you wrote this for everyone who isn't you?

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/commit/706cd670a909b75d01adb9c5be00be021104e565

**Comment by samdark** [comment]
Thanks!
