### ISSUE TITLE
Documentation for custom response.

### ISSUE THREAD

**Issue by doublehops** [samdark/yii2-cookbook#44]
I'm interested in creating a custom XML response but the document* is not complete so I'm unsure how this can be done. If someone can point me into the right direction, I'll be happy to document this myself once I know.

* https://github.com/samdark/yii2-cookbook/blob/master/book/response-formats.md#custom-response

**Comment by samdark** [comment]
What do you mean by *custom* XML response?

**Comment by doublehops** [comment]
It's in reference to this post* in the forum. I'm quite stuck in how I can change the output.

Damien

* http://www.yiiframework.com/forum/index.php/topic/63036-trouble-returning-custom-xml-in-api-request/

On 8 April 2015 17:58:45 GMT+10:00, Alexander Makarov <notifications@github.com> wrote:
>What do you mean by *custom* XML response?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/samdark/yii2-cookbook/issues/44#issuecomment-90835501

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/5996
