### ISSUE TITLE
Using multiple gridviews + pagination

### ISSUE THREAD

**Issue by samdark** [samdark/yii2-cookbook#45]
In case of multiple paginated GridViews on the same page one should specify `Pagination::$pageParam` else pages of both grids will be changed.

**Comment by summerknight** [comment]
What about now? How to solve such problem?

**Comment by cebe** [comment]
this is already covered in the guide: http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html#multiple-gridviews-on-one-page

**Comment by samdark** [comment]
Thanks for pointing it out.

**Comment by koredalin** [comment]
Whatever I do by the guide - I have 3 GridViews. 1 Pagination (only for the last model). Only the last model GridView is updated.
Is there a way that I have a pagination for each view?
Thank you.

**Comment by antonmarin** [comment]
no pjax? have you tried changing your pagination attribute?

**Comment by koredalin** [comment]
I use pjax without any parameters. It starts before the three GridViews and ends after them.

**Comment by koredalin** [comment]
Excuse me. I had no enough records in the Database.
I'm sorry about the spam.
Thank you - once again.
