### ISSUE TITLE
yii2 cookbook(chinese version)

### ISSUE THREAD

**Issue by flamerecca** [samdark/yii2-cookbook#47]
Hello. I'm trying to make a chinese version of yii 2 cookbook. May I just fork the file and start translating? (Sorry its my first time, quite nervous about translating things on github)

Any suggestion are welcome. Thank you.

**Comment by samdark** [comment]
It's quite early to start translating it but if you want to do it I can prepare some tools.

Generally I think it could follow the same workflow as Yii guide i.e. fork repo, create `book-zh-CN` and start translation there.
