### ISSUE TITLE
Offline app documentation

### ISSUE THREAD

**Issue by rubenheymans** [samdark/yii2-cookbook#55]
Goal: Continue working while there is (temporarily) no internet connection

Use localstorage, firebase, ...
http://www.html5rocks.com/en/tutorials/offline/whats-offline/

Sync offline data with server database after (re)connnection with internet

**Comment by samdark** [comment]
That's interesting topic but it doesn't have much about Yii.

**Comment by samdark** [comment]
Decided not to cover it.

**Comment by tunecino** [comment]
I agree, Offline is a very interesting as topic but it have more to do with browsers support, HTML5 and front-end frameworks, a good cashing strategy may have more to do with Yii.

**Comment by rubenheymans** [comment]
so what about a cache cookbook?
https://www.digitalocean.com/community/tutorials/how-to-use-caching-with-the-yii-framework-to-improve-performance

Do you have any experience with offline apps using a php framework? Helpfull url's?
