### ISSUE TITLE
About IDE autocompletion for Yii::createObject

### ISSUE THREAD

**Issue by ouewqa** [samdark/yii2-cookbook#70]
```
/**
* add question follow
*/
public function dealWithAddFollowQuestion()
{
        $model = Yii::createObject(FollowQuestionEntity::className());
        $model->addFollow($this->owner->id, $this->owner->create_by);
}
```
$model is created by Yii::createObject
And how to let $model auto hints?

**Comment by githubjeka** [comment]
via phpDoc `@var FollowQuestionEntity $model`

**Comment by ouewqa** [comment]
I put phpDoc 
```
/** @var FollowQuestionEntity $model */ 
```
before
```
$model->addFollow($this->owner->id, $this->owner->create_by);
```
or before
```
public function dealWithAddFollowQuestion()
{
    ...
}
```

or before
```
class QuestionBehavior extends Behavior{...}
```

All doesn't work

**Comment by samdark** [comment]
Which IDE?

**Comment by ouewqa** [comment]
PHPStorm v9

**Comment by samdark** [comment]
Weird. Is FollowQuestionEntity imported via `use`? If not you need fully qualified class name i.e. with namespace.

**Comment by ouewqa** [comment]
FollowQuestionEntity imported via use common\entities\FollowQuestionEntity;

Can you give me a Integrity code example, Maybe you put phpDoc in the wrong place.

**Comment by samdark** [comment]
```php
/** @var FollowQuestionEntity */
$model = Yii::createObject(FollowQuestionEntity::className());
```

**Comment by ouewqa** [comment]
It works! Thanks.

Should put the PHPDOC before Yii::createObject();
