### ISSUE TITLE
Дублируется метод prepare()

### ISSUE THREAD

**Issue by evgenmil** [samdark/yii2-cookbook#84]
Здравствуйте.
Подскажите, пожалуйста, может конечно, я что-то делаю не так.
Делаю простое наследование модели по типу (по категории товара).
```php
namespace app\models;
use app\models\query\GoodPhoneQuery;

class GoodPhone extends GoodItems
{
    /**
     * @inheritdoc
     * @return \app\models\query\GoodPhoneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new GoodPhoneQuery(get_called_class());
    }
}
```
app\models\query\GoodPhoneQuery :
```php
namespace app\models\query;
use yii\db\ActiveQuery;

class GoodPhoneQuery extends ActiveQuery
{
    public function prepare($builder)
    {
        $this->distinct();
        $this->joinWith('goods.category');
        $this->andWhere('ix_category_goods = 74'); // категория товара хранится в таблице category
        return parent::prepare($builder);
    }
}
```
Делаю запрос:
```php
public function actionSelectPhone()
    {
        $query = GoodPhone::find();
        VarDumper::dump($query->count(), 3, true);
    }
```
Появляется исключение `SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'goods'.`
Вывел sql через `getRawSql()` понял, что метод prepare() отработал два раза.
В чем может быть причина? и правильно ли я делаю?
Заранее благодарю!

**Comment by samdark** [comment]
Который из них отработал два раза?

**Comment by evgenmil** [comment]
Оба метода:
```php
$this->joinWith('goods.category');
$this->andWhere('ix_category_goods = 74');
```
отработали два раза, т.е. присутствуют в итоговом SQL-запросе.

**Comment by samdark** [comment]
Что-то тут не так... не должен сам по себе prepare вызываться два раза.

**Comment by evgenmil** [comment]
Согласен. Когда вызываю метод all(), то все в порядке. Отрабатывает, как нужно.
Такое случается только при вызове метода count().
Здесь https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L391 метод prepare() отрабатывает два раза и срабатывает исключение.

**Comment by samdark** [comment]
Сесть и разобраться пока не могу. Кидайте в gitter или на форумы. О результатах отпишитесь здесь.

**Comment by samdark** [comment]
Issue пока закрыл так как собственно к кукбуку отношения не имеет.
