### ISSUE TITLE
Assets publishing and minifying - how?

### ISSUE THREAD

**Issue by summerknight** [samdark/yii2-cookbook#93]
**Issue related to this recipe:**

[Asset processing with Grunt](https://github.com/samdark/yii2-cookbook/blob/master/book/structure-asset-processing-with-grunt.md)

* There are a lot of beautiful Yii2 widgets [ex. Kartik ones](https://github.com/kartik-v/yii2-widgets)
* It is better to have all .css compressed into one min.css (same for .js)
* Yii widgets by default publish .css and .js to web/assets folder

* If I disable assets management then widgets doesn't work (or some errors are occurred)
* If I enable it I have a lot of separated sources loaded from web/assets folder.

How to use Yii widgets and have only one .css and .js source file?

**Thanks in advance!**

**Comment by samdark** [comment]
Use widget assets via grunt same way as your app assets.
